### ISSUE TITLE
service is down

### ISSUE THREAD

**Issue by vn971** [cschneid/irclogger#11]
irclogger_com  is offline, no chats aviable after 06:50 even in popular channels like #mongodb

If I shouldn't open issues in such cases -- please, write, I won't.

**Comment by cschneid** [comment]
Yeah, the underlying bot has a habit of crashing, typically overnight when I wouldn't notice.  I've been meaning to 1) install monit and make it keep it up, and 2) stop using the silly perl bot I borrowed.

Thanks for letting me know. You can also email me directly at chris@christopher-schneider.com.
