### ISSUE TITLE
Is it possible to get the irc log in json format?

### ISSUE THREAD

**Issue by shankardevy** [cschneid/irclogger#12]
I wanted to get the data of a channel for a particular date in json format.
for eg: http://irclogger.com/.elixir-lang/2014-12-09.json

I read through the code but noticed that it's not currently implemented. Will you be interested in a PR?

**Comment by cschneid** [comment]
I've let this project lapse. I don't think its actually collecting data currently.

Maybe at some point I'll rewrite it, but its not coming soon

If you send a PR, I'll merge it, but I am not sure how useful it'd be :smiley:

**Comment by shankardevy** [comment]
Sorry I do not understand what you mean by 

> I've let this project lapse. I don't think its actually collecting data currently.

is this not the repo that powers http://irclogger.com? I see this repo is linked from  http://irclogger.com

  16:51 IRCLogger was written in Sinatra, an awesome Ruby microframework. The source code is   available on GitHub.
  16:51 Please contact me at chris@christopher-schneider.com
  16:51 Check out my blog about Sinatra and Ruby.
  16:51 Thanks a ton to Damian Janowski for the amazing theme.

and I am using the data collected in  http://irclogger.com for elixir-lang channel even today. The below link gives me current data.

http://irclogger.com/.elixir-lang/2014-12-10

I am studying some old data in the log and having a json format would help me greatly.

Thanks for your help

**Comment by cschneid** [comment]
Yeah, the website is up at irclogger.com, but the daemon that collects data isn't working, and hasn't worked for a while. 

I may get around to reviving it, but it'll be a while until I do.

**Comment by shankardevy** [comment]
I see irclogger.com has the data for elixir-lang till date. so not sure if daemon is not working.

I am looking at doing some experimental stuff with the elixir-lang channel log and badly need to access the log for my experiment. 

Is this something that you can help me with? I will be grateful (of course, I am already grateful to you for what you have in irclogger.com in html now.)

**Comment by shankardevy** [comment]
@cschneid just basically asking you the same question as my previous comment. 

irclogger.com has some historical data on channels that I want to experiment with. 
I need to access the historical data in json format to reconstruct the db on my local machine or a one time access to database dump file. Is it something that you can help with?

Thanks

**Comment by shankardevy** [comment]
@cschneid actually you already have what I need :) Just that I need to read through the code to see. Thanks.

http://irclogger.com/.elixir-lang/slice/1419013800/1419100200
