### ISSUE TITLE
Internal server error on sliced data

### ISSUE THREAD

**Issue by shankardevy** [cschneid/irclogger#13]
Hi,
Going to http://irclogger.com/.elixir-lang/slice/1422264563/1422350963 gives me Internal Server error. Earlier it was working properly and giving me json data. Now it's not working. Is it possible to correct this error?

Thanks

**Comment by shankardevy** [comment]
Hi, 
is it possible to correct the error that has happened recently? Thanks

**Comment by shankardevy** [comment]
Hi,
Just want to add that I am looking for some historical data from irclogger.com for use in http://irc.programmingelixir.com that allows searching logs for elixir-lang channel.

I understand you might be busy. If you need any help from my end to resolve it, please let me know.

**Comment by cschneid** [comment]
Ok. I'll look at this over the weekend.

**Comment by shankardevy** [comment]
Thank you. Much appreciated

**Comment by cschneid** [comment]
Seems to be fixed. Have fun!

**Comment by shankardevy** [comment]
thank you very much.
