### ISSUE TITLE
How does the database get populated with IRC?

### ISSUE THREAD

**Issue by epitron** [cschneid/irclogger#6]
I know it seems like an obvious question, but there's no hint anywhere in the project's directory. :)

**Comment by cschneid** [comment]
Heh, it's a magic trick.

Specifically a perl magic trick that's not in the repo.  I'm using ilbot2.pl to do the logging, this repo is front-end only.

There's a 75% done branch 'bot' that I should probably finish up at some point. Which has the logging bot in ruby.

And I plan on porting this whole project over to torquebox as an experiment.  Which should be fun, and have the bot in process.

**Comment by epitron** [comment]
Hmm.. the ruby and the torquebox solutions sound a lot more complicated than throwing ilbot2.pl into the repo. Why not just do that? :)

**Comment by cschneid** [comment]
Yep, way overkill.  But I wanna learn torquebox, and had them add a long-running-process feature to it last week, just for irclogger support (and because it's useful).

Expect to see things migrated over the next week or so.

**Comment by cschneid** [comment]
Ohh, and yeah, I'll throw ilbot into the repo too, so people can use the older, non-torquebox mode.... For those who don't want to spend 1+ gigs running a full java app server just to log irc.

**Comment by epitron** [comment]
You're too kind. ^_^

**Comment by epitron** [comment]
BTW, if you want to write really quick and easy Ruby IRC bots, there's a framework a friend wrote called Marvin. Here's a bot I wrote with it:

https://github.com/epitron/pookie

As you can see, you need almost no code. :)

**Comment by andypiper** [comment]
Did the Ruby IRC bot portion of this ever get written / published?

Any info on how to setup the database?

**Comment by cschneid** [comment]
There's a branch, but it's not done yet. As I commented on the other issue, I'll shift it up my TODO list, and see if I can get it done soonish.

**Comment by andypiper** [comment]
noted.

**Comment by andypiper** [comment]
actually currently hacking on Scribe https://github.com/andypiper/scribe which is Sinatra on the front with Isaac on the back, and a DB in the middle.
